[tool.poetry]
name = "crypto_plus"
version = "0.1.1"
description = "A Easy-to-use Crypto Tool"
readme = "README.md"
authors = ["wmymz <wmymz@icloud.com>"]
license = "MIT"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = "^3.12"
cryptography = "^41.0.7"
pycryptodome = "^3.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
tox = "^4.5.2"
mkdocs = "^1.4.3"
mkdocs-material = "^8.5.11"
ruff = "^0.1.9"

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.pytest.ini_options]
testpaths = "tests"
python_files = "tests.py test_*.py *_tests.py"
